# Exported from Render on 2026-05-05T15:06:07Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: n8n-hosting
      runtime: docker
      repo: https://github.com/mpointcgr/n8n-hosting
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
